# This is a basic workflow to help you get started with Actions

name: Validate Gradle Wrapper

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
 [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
 
